// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_law_firm: dynamic(() => import("./AboutLawFirm")),
  biography: dynamic(() => import("./Biography")),
  case_results: dynamic(() => import("./CaseResults")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  pratice_areas: dynamic(() => import("./PraticeAreas")),
  rich_text: dynamic(() => import("./RichText")),
};
